2021-07-13 18:46:38,068 file.manager INFO 1.2.2
2021-07-13 18:46:38,068 file.manager INFO Copyright (C) 2003-2020, Noriaki Ando and OpenRTM development team,
2021-07-13 18:46:38,068 file.manager INFO   Intelligent Systems Research Institute, AIST,
2021-07-13 18:46:38,068 file.manager INFO Copyright (C) 2020, Noriaki Ando and OpenRTM development team,
2021-07-13 18:46:38,068 file.manager INFO   Industrial Cyber-Physical Research Center, AIST,
2021-07-13 18:46:38,069 file.manager INFO   All right reserved.
2021-07-13 18:46:38,069 file.manager INFO Manager starting.
2021-07-13 18:46:38,069 file.manager INFO Starting local logging.
2021-07-13 18:46:38,074 file.manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2021-07-13 18:46:42,181 file.ManagerServant INFO Master manager not found
2021-07-13 18:46:42,183 file.LocalServiceAdmin INFO All the local services are enabled.
2021-07-13 18:46:42,187 file.manager INFO Component type conf file: Test2.conf loaded.
2021-07-13 18:46:42,190 file.ec_base INFO setRate(1000000.000000) done
2021-07-13 18:46:42,191 file.ec_base INFO setRate(1000.000000) done
2021-07-13 18:46:42,191 file.rtobject INFO 1 execution context was created.
2021-07-13 18:46:42,192 file.rtobject INFO Initial active configuration set is default-set.
2021-07-13 18:46:51,704 file.SdoServiceAdmin WARNING No available SDO service in the factory: 
2021-07-13 18:46:51,704 file.SdoServiceAdmin ERROR type  already exists.
2021-07-13 18:46:57,052 file.ManagerServant INFO Master manager not found
2021-07-13 18:47:11,989 file.ManagerServant INFO Master manager not found
2021-07-13 18:47:26,971 file.ManagerServant INFO Master manager not found
2021-07-13 18:47:36,729 file.InPortCorbaCdrConsumer ERROR Traceback (most recent call last):
  File "C:\Users\kouhe\AppData\Local\Programs\Python\Python38\lib\site-packages\OpenRTM_aist\InPortCorbaCdrConsumer.py", line 157, in put
    return self.convertReturnCode(inportcdr.put(data))
  File "C:\Users\kouhe\AppData\Local\Programs\Python\Python38\lib\site-packages\OpenRTM_aist\RTM_IDL\DataPort_idl.py", line 79, in put
    return self._obj.invoke("put", _0_OpenRTM.InPortCdr._d_put, args)
omniORB.CORBA._omni_sys_exc: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)

